### ISSUE TITLE
젠킨스 CI/CD 인프라 구축

### ISSUE THREAD

**Issue by Hugh-KR** [Ludo-SMP/ludo-backend#54]
- jenkins 도입
- 별도의 vm 인스턴스 구축하여 사용

**Comment by june-777** [comment]
### 환경 변수 관리 방법 논의
@Hugh-KR @zxcev 

**문제점**
기존에는 로컬 환경에서 `.env 파일을 관리 및 빌드`했기 때문에 문제가 없었습니다.
하지만 `젠킨스 클라우드 인스턴스` 환경에서는 `.env 파일`이 없기 때문에 빌드 과정에서 문제가 발생합니다.

**해결 방법**
1. `.env 파일` 을 `젠킨스 클라우드 인스턴스`에서 관리
장점: 쉽습니다.
단점: 로컬 환경의 `.env` 파일과 클라우드 환경의 `.env` 파일의 동기화를 신경써줘야 합니다.

2. 쉘 스크립트로 환경 변수 설정
장점: 제 생각에는 큰 장점은 없어보입니다.
단점: 마찬가지로 동기화에 신경써줘야 합니다.

3. 환경 설정 관리용 프라이빗 레포를 서브 모듈로 등록
장점: 동기화 이슈 x
단점: 초기 세팅

저는 장,단점의 이유로 3번 방법이 합리적이라 생각들긴 합니다. 진행 전에 간단한 논의를 하면 좋을 것 같아서 코멘트 드립니다.

**Comment by Hugh-KR** [comment]
저도 3번에 동의합니다. 필요하다면 `Spring Cloud Config`를 적용할 수 있는 확장성 높은 해결 방법 이라고 생각해요.

**Comment by june-777** [comment]
@zxcev
생각하지 못한 방법인데, 좋은 인사이트를 남겨주셔서 감사합니다 👍
가격또한 gcp 한달 기준 약 127원 (0.002$ 데이터 저장 + 0.005$ 데이터 처리 +  0.12$ 네트워크 사용량)으로 합리적이네요.

만약 도입하게 된다면, `.env` 파일만 cloud storage로 관리하게 될 것 같아요.
추 후 cloud storage로 관리해야 할 데이터들이 추가로 생길 때, 말씀하신 방안을 고려해봐도 좋을 것 같습니다 👍

현재는 프라이빗 레포를 서브 모듈로 활용하는 방안으로 진행하려고 합니다! 좋은 의견 감사합니다  🙂

---
Reference (gcp cloud storage 가격 책정)
https://cloud.google.com/storage/pricing?hl=ko#operations-by-class
https://cloud.google.com/storage/pricing-examples?hl=ko#prorate

**Comment by Hugh-KR** [comment]
@Hugh-KR 
동의합니다. 현재도 scale-out이 많이 되어 있는 상황이라, 서버간 의존성은 최대한 낮추는 방법이 합리적인 것 같아요.
물론 github private repo도 클라우드 Saas 같은 느낌이긴 하지만 검증된 클라우드 서비스라고 생각하겠습니다..ㅎㅎ

**Comment by june-777** [comment]
PR Merge & Closed: https://github.com/Ludo-SMP/ludo-backend/pull/106
