### ISSUE TITLE
모집 공고 목록 조회 API Response 명세 수정 내역 반영

### ISSUE THREAD

**Issue by june-777** [Ludo-SMP/ludo-backend#73]
##### 모집 공고 목록 조회 API, 인기 모집 공고 목록 조회 API
현재: `positions`, `stacks`, `categories` 리스트에 `string`만 포함
변경사항: `id`, `string` 포함, `stacks`의 경우 `imageUrl`도 포함

다른 API Response 명세와 통일성이 있으면 좋겠다는 @SungHyun627 님의 의견이 있었습니다.
이를 수정 반영하겠습니다.

**Comment by Hugh-KR** [comment]
👍👍
