### ISSUE TITLE
운영용 데이터베이스 서버 DDL 별도 작업 필요

### ISSUE THREAD

**Issue by june-777** [Ludo-SMP/ludo-backend#89]
## 이슈
현재까지는 개발단계였기 때문에, `JPA auto-ddl: create` 으로 사용중이었어요.
이제 실 사용자도 받아보고 운영단계로 들어서기 때문에 `auto-ddl` 옵션은 끄고, 데이터베이스에서 직접 DDL(테이블 생성, 제약조건 추가, etc) 작업이 필요해요.

**필요한 이유**
- 현재 데이터베이스의 제약 조건 이름 (Constraint_name) 을 확인해보면, 아래와 같이 식별하기 어려운 문자열 값으로 세팅되어 있어요.
- 식별이 매우 어려운 제약조건 이름이기 때문에, 운영 단계에서 그대로 사용하기엔 무리가 있어요. (디버깅이 어려워요)
<img width="894" alt="image" src="https://github.com/Ludo-SMP/ludo-backend/assets/68291395/c7fd23df-55b8-4b45-be36-4052bacaa3b5">

1. `JPA auto-ddl: create` 에서 생성된 DDL 문을 조금 다듬어서 공유드릴게요.
2. 검토가 완료되면, 다음 배포 때 데이터베이스 서버에 반영할게요.

**Comment by Hugh-KR** [comment]
@june-777 
그렇네요, 디버깅이 어려운 문제에 더해 auto-ddl 설정을 바꿔가는 과정에서 휴먼 에러 발생 가능성도 높아질 것 같아요.
운영 서버에서는 validate 또는 none 옵션을 붙여서 명시해주면 될 듯 합니다. 저는 찬성이에요.

(관련된 재미있는 영상 하나 발견해서 공유 드립니다. https://www.youtube.com/watch?v=SWZcrdmmLEU)

**Comment by june-777** [comment]
@Hugh-KR @zxcev 
## 변경사항 공유
### 변경 사항 정리
1. 테이블 컬럼 위치 보기 좋게 변경
	이전에는 pk, fk 위치 등이 중구난방
1. FK, UK 제약조건 이름 변경
	네이밍: `테이블이름_대상테이블이름_fk`, `테이블이름_대상테이블이름_uk`
	기본키 이름은 `PRIMARY`로 유지
3. `recruitment_position_lnk` 기본키 컬럼 위치 변경
	PK(position_id, recruitment_id) → PK(recruitment_id, position_id)
4. 테이블 이름 변경
        applicant → recruitment_user_lnk
        participant → study_user_lnk

---
**JPA Auto DDL 제약조건 (변경 전 전체)**
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/6f0fe79b-25bd-44f2-beab-efc2918c30cf)
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/ea9a52b5-3b6e-405f-8f6d-0228dfe12c2a)

<br><br>
**applicant (recruitment_user_lnk) 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/9a522661-cc73-4212-b148-6f6da2ada004)

`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/152faf88-4f45-4ac1-ad23-cfafa54511f5)


<br><br>
**category 제약조건** 
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/7cf7a391-39cc-40dc-b863-64c90636a3c1)


<br><br>
**participant (study_user_lnk) 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/083f55a6-a265-4467-a786-bb63c525e3f6)

`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/cc1bb301-4c5d-4974-ac41-18a42b51b0f6)


<br><br>
**position 제약조건**
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/fbc39088-7332-4b43-b3a0-c07c0811800a)


<br><br>
**recruitment 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/4d3c2ea5-ba4e-4c56-967d-336d0c2fdcdd)
`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/2da05864-b3bd-4d47-9d3f-f58d784ac386)


<br><br>
**recruitment_position_lnk 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/29230112-35f1-407e-9023-23afb7dff00a)

`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/0fab58bb-8744-4534-ad86-0b878421103d)


<br><br>
**recruitment_stack_lnk 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/9085afcb-599b-4766-a606-c26d3bea0e08)
`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/a26adc1b-6592-4e8c-9c4f-b6622f52780a)


<br><br>
**stack 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/d0ce7518-6614-4f97-9094-95581267c231)
`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/6795a8e8-4fec-454c-9af2-9242f07c6626)


<br><br>
**stack_category 제약조건**
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/fda95a93-8587-4862-92ec-015c33c9c297)


<br><br>
**study 제약조건**
`변경 전`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/75f39916-0a45-464f-b2a4-354f30587b4d)

`변경 후`
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/39a8da2e-3978-4d42-94cd-5fa78916ebb8)


<br><br>
**user 제약조건**
![image](https://github.com/Ludo-SMP/ludo-backend/assets/68291395/996f2301-2d87-4a96-bfd3-29b60b9258d1)

**Comment by Hugh-KR** [comment]
@june-777 
캬, 정말 고생 하셨습니다. 
확인 완료 입니다!
